### ISSUE TITLE
Why hasn't it been updated? Please hurry up!!!

### ISSUE THREAD

**Issue by qiyugfh** [Ezbeat/AntiVirtualMachine#2]
I don't how to detect the VirtualPC, VirtualBox, KVM and so on.

**Comment by Ezbeat** [comment]
I do not just consider hosted virtualization solutions like Vmware and VirtualBox as you wish. Hypervisior type virtual environments such as KVM are under investigation to be able to detect them.
But I do not think the progress will be fast because I'm in the company. I will be thankful if you can wait till someday.
